import type { Metadata } from 'next';

import './globals.css';
import { ThemeProvider } from '@/components/ui/theme-provider';
import { ModeToggle } from '@/components/mode-toggle';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <body className="">
        <div className="mx-auto max-w-xl border-x border-zinc-700">
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <header className="flex w-full items-center justify-between border-b border-zinc-700 p-2">
              <div className="size-10" />
              <h1 className="text-xl font-bold">taik mate</h1>
              <ModeToggle />
            </header>
            <main className="flex min-h-[calc(100svh-4rem)] flex-col items-center justify-center">
              {children}
            </main>
          </ThemeProvider>
        </div>
      </body>
    </html>
  );
}
